name: Tests

on: [ push, pull_request, workflow_dispatch ]

env:
  PORT: 3000
  NODE_ENV: development
  RATE_LIMIT_REQUEST: 10
  DB_CONFIG: ${{secrets.DB_CONFIG}}
  ADMIN_KEY: ${{secrets.ADMIN_KEY}}
  TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: node16

      - name: Install Node dependencies
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: TSLink
        run: yarn lint
